#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Generate revised Table 8 for CODA.

Inputs
------
coda_channel_event_level.csv
coda_channel_seed_level.csv

These files are generated by Tab8_comm_channels.py.

Outputs
-------
table8_operational_activity.csv
table8_operational_activity.tex
table8_seed_level_audit.csv
"""

from pathlib import Path

import numpy as np
import pandas as pd


# ============================================================
# CONFIGURATION
# ============================================================

EVENTS_CSV = Path("../results/analysis/communication_channels/coda_channel_event_level.csv")
SEED_CSV = Path("../results/analysis/communication_channels/coda_channel_seed_level.csv")

OUTPUT_SEED = Path("table8_seed_level_audit.csv")
OUTPUT_CSV = Path("table8_operational_activity.csv")
OUTPUT_TEX = Path("table8_operational_activity.tex")

# Operational thresholds used only for descriptive auditing.
NEAR_MAX_THRESHOLD = 0.95
HISTORY_ENVELOPE_TOL = 0.01

EXPECTED_SEEDS = 10

ENVIRONMENTS = [
    "HalfCheetah-v5",
    "Hopper-v5",
    "Swimmer-v5",
    "Walker2d-v5",
]


# ============================================================
# HELPERS
# ============================================================

def numeric(series):
    """Convert a pandas Series to numeric."""
    return pd.to_numeric(series, errors="coerce")


def median_q1_q3(series):
    """
    Return median, Q1, Q3 using pandas quantiles.
    """
    x = numeric(series)
    x = x[np.isfinite(x)]

    if len(x) == 0:
        return np.nan, np.nan, np.nan

    return (
        float(x.median()),
        float(x.quantile(0.25)),
        float(x.quantile(0.75)),
    )


def fmt_median_iqr(
    row,
    prefix,
    scale=1.0,
    digits=1,
):
    """
    Format:
        median [Q1, Q3]
    """
    med = row[f"{prefix}_median"] * scale
    q1 = row[f"{prefix}_q1"] * scale
    q3 = row[f"{prefix}_q3"] * scale

    if not (
        np.isfinite(med)
        and np.isfinite(q1)
        and np.isfinite(q3)
    ):
        return "--"

    return (
        f"{med:.{digits}f} "
        f"[{q1:.{digits}f}, {q3:.{digits}f}]"
    )


# ============================================================
# LOAD DATA
# ============================================================

if not EVENTS_CSV.exists():
    raise FileNotFoundError(
        f"{EVENTS_CSV} not found. "
        "Run Tab8_comm_channels.py first."
    )

if not SEED_CSV.exists():
    raise FileNotFoundError(
        f"{SEED_CSV} not found. "
        "Run Tab8_comm_channels.py first."
    )


events = pd.read_csv(EVENTS_CSV)
original_seed = pd.read_csv(SEED_CSV)


required_event_columns = [
    "learner",
    "environment",
    "training_seed",
    "guided_update",
    "event_status",
    "u_effective",
    "warmup_gain",
]

missing = [
    c for c in required_event_columns
    if c not in events.columns
]

if missing:
    raise RuntimeError(
        f"Missing event columns: {missing}"
    )


required_seed_columns = [
    "learner",
    "environment",
    "training_seed",
    "i2o_valid_rate",
    "i2o_state_median",
    "i2o_near_saturation_rate",
]

missing = [
    c for c in required_seed_columns
    if c not in original_seed.columns
]

if missing:
    raise RuntimeError(
        f"Missing seed-level columns: {missing}"
    )


# ============================================================
# O2I SEED-LEVEL METRICS
# ============================================================

seed_rows = []

group_columns = [
    "learner",
    "environment",
    "training_seed",
]


for (
    learner,
    environment,
    training_seed,
), group in events.groupby(group_columns):

    # --------------------------------------------------------
    # Guided inheritance events
    # --------------------------------------------------------

    guided = group[
        numeric(group["guided_update"]) >= 0.5
    ].copy()

    n_guided = len(guided)

    # --------------------------------------------------------
    # Active O2I events
    # --------------------------------------------------------

    active = guided[
        guided["event_status"] == "active"
    ].copy()

    n_active = len(active)

    o2i_active_rate = (
        n_active / n_guided
        if n_guided > 0
        else np.nan
    )

    # --------------------------------------------------------
    # U_eff and history gain
    # --------------------------------------------------------

    u_eff = numeric(
        active["u_effective"]
    )

    omega = numeric(
        active["warmup_gain"]
    )

    valid = (
        np.isfinite(u_eff)
        &
        np.isfinite(omega)
    )

    u_eff = u_eff[valid]
    omega = omega[valid]

    # --------------------------------------------------------
    # Near-maximal intervention
    #
    # P(U_eff >= 0.95 | O2I active)
    # --------------------------------------------------------

    if len(u_eff) > 0:
        near_max_rate = float(
            np.mean(
                u_eff >= NEAR_MAX_THRESHOLD
            )
        )
    else:
        near_max_rate = np.nan

    # --------------------------------------------------------
    # Operation near the retained-history envelope
    #
    # P(|U_eff - omega| <= 0.01 | O2I active)
    # --------------------------------------------------------

    if len(u_eff) > 0:
        history_envelope_rate = float(
            np.mean(
                np.abs(
                    u_eff - omega
                )
                <= HISTORY_ENVELOPE_TOL
            )
        )
    else:
        history_envelope_rate = np.nan

    seed_rows.append(
        {
            "learner": learner,
            "environment": environment,
            "training_seed": training_seed,

            "n_guided_events": n_guided,
            "n_active_events": n_active,

            "o2i_active_rate":
                o2i_active_rate,

            "o2i_near_max_rate":
                near_max_rate,

            "o2i_history_envelope_rate":
                history_envelope_rate,
        }
    )


o2i_seed = pd.DataFrame(seed_rows)


# ============================================================
# ADD I2O METRICS FROM ORIGINAL TABLE-8 ANALYSIS
# ============================================================

i2o_columns = [
    "learner",
    "environment",
    "training_seed",
    "i2o_valid_rate",
    "i2o_state_median",
    "i2o_near_saturation_rate",
]

i2o_seed = (
    original_seed[i2o_columns]
    .copy()
)


seed_summary = pd.merge(
    o2i_seed,
    i2o_seed,
    on=[
        "learner",
        "environment",
        "training_seed",
    ],
    how="left",
    validate="one_to_one",
)


# ============================================================
# DESIGN VALIDATION
# ============================================================

seed_counts = (
    seed_summary
    .groupby(
        [
            "learner",
            "environment",
        ]
    )["training_seed"]
    .nunique()
)

print("\nSeeds per learner/environment")
print("=" * 70)
print(seed_counts)

bad = seed_counts[
    seed_counts != EXPECTED_SEEDS
]

if not bad.empty:
    raise RuntimeError(
        "Expected 10 seeds per learner/environment:\n"
        f"{bad}"
    )


# ============================================================
# SAVE SEED-LEVEL AUDIT
# ============================================================

seed_summary.to_csv(
    OUTPUT_SEED,
    index=False,
)


# ============================================================
# AGGREGATE ACROSS TRAINING SEEDS
# ============================================================

METRICS = [
    "o2i_active_rate",
    "o2i_near_max_rate",
    "o2i_history_envelope_rate",
    "i2o_valid_rate",
    "i2o_state_median",
    "i2o_near_saturation_rate",
]


summary_rows = []


for (
    learner,
    environment,
), group in seed_summary.groupby(
    [
        "learner",
        "environment",
    ]
):

    row = {
        "learner": learner,
        "environment": environment,
        "n_seeds":
            group["training_seed"].nunique(),
    }

    for metric in METRICS:

        med, q1, q3 = median_q1_q3(
            group[metric]
        )

        row[f"{metric}_median"] = med
        row[f"{metric}_q1"] = q1
        row[f"{metric}_q3"] = q3

    summary_rows.append(row)


summary = pd.DataFrame(summary_rows)


# ============================================================
# ORDER TABLE
# ============================================================

learner_order = {
    "PPO": 0,
    "SAC": 1,
}

environment_order = {
    env: i
    for i, env in enumerate(ENVIRONMENTS)
}


summary["_learner_order"] = (
    summary["learner"]
    .map(learner_order)
)

summary["_environment_order"] = (
    summary["environment"]
    .map(environment_order)
)

summary = (
    summary
    .sort_values(
        [
            "_learner_order",
            "_environment_order",
        ]
    )
    .drop(
        columns=[
            "_learner_order",
            "_environment_order",
        ]
    )
    .reset_index(drop=True)
)


# ============================================================
# CREATE DISPLAY TABLE
# ============================================================

display_rows = []


for _, row in summary.iterrows():

    display_rows.append(
        {
            "Learner":
                row["learner"],

            "Environment":
                row["environment"],

            "O2I active (%)":
                fmt_median_iqr(
                    row,
                    "o2i_active_rate",
                    scale=100.0,
                    digits=1,
                ),

            "Near-max (%)":
                fmt_median_iqr(
                    row,
                    "o2i_near_max_rate",
                    scale=100.0,
                    digits=1,
                ),

            "Hist.-env. (%)":
                fmt_median_iqr(
                    row,
                    "o2i_history_envelope_rate",
                    scale=100.0,
                    digits=1,
                ),

            "I2O valid (%)":
                fmt_median_iqr(
                    row,
                    "i2o_valid_rate",
                    scale=100.0,
                    digits=1,
                ),

            "Median S":
                fmt_median_iqr(
                    row,
                    "i2o_state_median",
                    scale=1.0,
                    digits=3,
                ),

            "S >= 0.95 (%)":
                fmt_median_iqr(
                    row,
                    "i2o_near_saturation_rate",
                    scale=100.0,
                    digits=1,
                ),
        }
    )


display_table = pd.DataFrame(
    display_rows
)


print("\nRevised Table 8")
print("=" * 140)
print(
    display_table.to_string(
        index=False
    )
)


display_table.to_csv(
    OUTPUT_CSV,
    index=False,
)


# ============================================================
# LATEX TABLE
# ============================================================

latex_lines = []

latex_lines.append(
    r"\begin{table*}[t]"
)

latex_lines.append(
    r"\centering"
)

latex_lines.append(
    r"\caption{Full-CODA operational activity, reported as median "
    r"$[Q_1,Q_3]$ across ten seeds. O2I near-maximal activity "
    r"denotes the within-seed fraction of active events with "
    r"$U_t^{\mathrm{eff}}\geq0.95$; history-envelope activity "
    r"denotes the fraction satisfying "
    r"$|U_t^{\mathrm{eff}}-\omega_t|\leq0.01$. "
    r"I2O statistics use genuine learner reports.}"
)

latex_lines.append(
    r"\label{tab:channel_activity}"
)

latex_lines.append(
    r"\setlength{\tabcolsep}{3.2pt}"
)

latex_lines.append(
    r"\renewcommand{\arraystretch}{1.05}"
)

latex_lines.append(
    r"\begin{tabular}{llcccccc}"
)

latex_lines.append(
    r"\hline"
)

latex_lines.append(
    r"Learner & Environment & "
    r"O2I active & Near-max & Hist.-env. & "
    r"I2O valid & Median $S$ & $S\geq0.95$ \\"
)

latex_lines.append(
    r" & & (\%) & (\%) & (\%) & (\%) & & (\%) \\"
)

latex_lines.append(
    r"\hline"
)


for _, row in summary.iterrows():

    learner = row["learner"]
    environment = row["environment"]

    active = fmt_median_iqr(
        row,
        "o2i_active_rate",
        scale=100.0,
        digits=1,
    )

    near_max = fmt_median_iqr(
        row,
        "o2i_near_max_rate",
        scale=100.0,
        digits=1,
    )

    hist_env = fmt_median_iqr(
        row,
        "o2i_history_envelope_rate",
        scale=100.0,
        digits=1,
    )

    i2o_valid = fmt_median_iqr(
        row,
        "i2o_valid_rate",
        scale=100.0,
        digits=1,
    )

    median_s = fmt_median_iqr(
        row,
        "i2o_state_median",
        scale=1.0,
        digits=3,
    )

    s95 = fmt_median_iqr(
        row,
        "i2o_near_saturation_rate",
        scale=100.0,
        digits=1,
    )

    latex_lines.append(
        f"{learner} & {environment} & "
        f"{active} & "
        f"{near_max} & "
        f"{hist_env} & "
        f"{i2o_valid} & "
        f"{median_s} & "
        f"{s95} \\\\"
    )


latex_lines.append(
    r"\hline"
)

latex_lines.append(
    r"\end{tabular}"
)

latex_lines.append(
    r"\end{table*}"
)


latex = "\n".join(
    latex_lines
)


OUTPUT_TEX.write_text(
    latex,
    encoding="utf-8",
)


# ============================================================
# FINAL REPORT
# ============================================================

print("\nFiles generated")
print("=" * 70)

print(
    f"Seed-level audit : {OUTPUT_SEED.resolve()}"
)

print(
    f"CSV table        : {OUTPUT_CSV.resolve()}"
)

print(
    f"LaTeX table      : {OUTPUT_TEX.resolve()}"
)